version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: [ "java", "-jar", "/app/app.jar" ]

